kind: ENC[AES256_GCM,data:P+E9ftTc,iv:CefNNRbs1bnpWd7UfzT2lDWXGrOwA5xiDs+R6eZJTNk=,tag:tXVt+7Bd+uadOlq+gLWKkA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xgyymTUWhZV8JA==,iv:rPg1WQ9ErbbP5im+rWMa8AFi9Xl+h4hGVumo5hT+pnU=,tag:VZhUKoqiiJNjqvApYQKukw==,type:str]
stringData:
    key: ENC[AES256_GCM,data:q/QV+9gwbgskmN8ANUNRZVJmLPEhhcRXunwokHXtA57aRYyN9zz5YSiJ32QSPAr/qDE/G13p4f1/IXVwU25b+0LzTuEoic03RTmUabAyXDvAcBmIokMfQy2cg2LivdXAo0G8K78E6/6SVhBucTpMLMUIaDz6Xlre0ks87G4ZlX0Q8D2W+8x70R3tNW+OHVaS4VAlLaZse915CAqYQWRNqdvuqwKHTNSGxt6C1+jBAsnWtSJ9EZvQkzLcF0TkMr6nt5DTAbINYuSJrgdy5xA1cclfXkDIug4ruWkJoiZ/Upykbhc/pJAQ7JF6Z4+n02w9Q68UoxH3ZrVPqrNZXOEUOvkZx9OhkqFl7LmB773z9OPacHAK1XYAb1yAY1iu/9dOOf5Hddt3n5jhxcpDV3ivx67jSIlJxf6YNpaog1xx05SHgkGVrVVWASLtbrZCml2fDGRVUkkdGVDkS5yClGmobRGgNE7GwpDMNcg8ZxXnRcrNZhkArnrVw29HAEOGpDUeEtgtEmmMF21FOBqKPuhCYLBKVTqWuzb0ofo4Pn2RAEK6/q2ihAirNkiPUxIRutRqT8raSWt4WxZFcF0pvQf16JccahG+k/WOHT3xxwHCJUisTcydG1p7wFW5mjGv,iv:eUgvgD5m2j+9So6Feehaj7lKgqKg/+5y3iH3Z82kBBc=,tag:e/kCw0f3AQnN8+cXpPV0AA==,type:str]
sops:
    age:
        - recipient: age1h7y2etdv5r0nclaaavral84gcdd2kvvcu2h8yes3e3k3fcp03fzq306yas
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS21qWk4rL0tmeG9XQUVt
            eTRQaDBWZFpzTDJMM25CMGlKMk5SQS94cWk4CmNiWCs5Y3NRV2NhTEgxWjQ4RkdZ
            WktnSU5vZjFsMjRFeW5rM3gvQ29BQlEKLS0tIFg1TTg3bTlXRmQydHpxSUxQVkxH
            Wm5GSEpPRGVQWXd3VlJPNys0UjUyR0kKGUAovlHvQWVSE1RKfMYA/YKUAeris/MC
            bD22VYD5c9odEzIDYwyxYff9KguGhvxVxWYQSYL8NJzfmgaqmizQLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:33:10Z"
    mac: ENC[AES256_GCM,data:CbkEG7mcnZpqivkkLy2ZcUvKWzPDnZt/S3uJhpq1mzCOV9kYYeeUPDb3WqIMd6ZXmV+SISr/3x7pk+NHz4XtiBo1baOENMBy0UHf/eSQvHTaHa40f/djWf/JexfRRNkn3cUoJZLGc7YrwpYAJXcBThV0K12HUo88rbHHgOjt57Y=,iv:mbdXePhGzaSZnnQGOAeEGynCYEWPjFem1iET8BHo1MA=,tag:1EJpr0YR5BvTGb3dVkelBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
