{ ... }:
{
  # SSH client — low-latency multiplexed connections
  programs.ssh = {
    enable = true;
    extraConfig = ''
      # Reuse connections — eliminates handshake on subsequent sessions
      ControlMaster auto
      ControlPath ~/.ssh/sockets/%r@%h-%p
      ControlPersist 600

      # Fast connection setup
      AddKeysToAgent yes
      ServerAliveInterval 30
      ServerAliveCountMax 3
      Compression no
    '';
  };

  home.file.".ssh/authorized_keys" = {
    text = ''
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH1mPlgK5eEnwi65Pp5/6d40fc1VVNB5h+MW4zs939I1 nhat-buuuk
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW7bsFVlAs+xx6bS/+F3d0KQwkLEYC+sKkaXgTQ9zYJZ7P7JzcV+Om07a8JC5yG4ziAgK5hQw7625Oo3NXXgDtR3BFIpe/h5+mCHM/oK4bLy3Shu7pEYBYG/dI8xct+dQu5U3WyoLltKc10Ful2+hk/ttVMNeMberNKkxz/ulD11GhJ2Jh7Nz/4RNOsAmoMLZJNrD5n7TiWSvUD/thi0qmTlHzPE3v7VWMD9B9JWCelyfTaI2026mMN3SZ7ZZXu8Aj0pAs4aamFBoP1JOcCaz6LrKExcEMNNOTpii/XWHc2BRwOuiILaKMFr1b/sS7Kj1H1Ma+7H5yj2zJF12Xxiat nhath@Nhats-MacBook-Pro.local
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO2l2A8T7RANMQMhXsLjxC73px574LJfa2nWkYouPSd6 minhnhat97kg
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaB4rl/AnUqoG0JW6yMjzY1ddJaJN8RD0iJbJzcjMPWxV53TWwRpeHOPqmWhBwaJAi0ueK9GurofpqP0VDH311yoeI27UvTAkOglEKvIepo3F1v8z2vTD2AriwbVoqKqB3ZyPc2jo5BOCvtZJADkDzteOVn5nszT2x815FURVBnD4OhArDrmUcYmSNfLk/WZLA06YJRWsXKLuzEhxzcBuatdtFurV4GqcIk0/oeZf+gIpqx/bLkhHyOJXO0wr/R0K5doT6MWtW6RSlQ49j+0Y1hfDrAw7S3RruBywz49o8lK3Z2Lqhnv9ox2nvM8yca4qfSADCrMjSGTcsv7RMJC8yTtzTZ1ZCriR37o5TkHcFHVHl9tgT/0MWPjo8IMJm7G5nUBRc7yQHiV4AxZkNaeJhPio0KrypsJbIlGbU4q/qW60YJI9ndoS7tT+UYsDBYOc76FUrCUfun/5Izop1JGola3TxIKOWgvZTtp4dSL0iDrWgoTVSMCGytokrmSmEaY8= nhath@Nathan-Macbook
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKW6ArdpBefiw9CbO/7So0CpLmTSK0OlRh0YjB2oy71R Generated By Termius
    '';
  };

  programs.lazygit = {
    enable = true;
    enableZshIntegration = false; # Disable lg() function, use simple alias instead
  };

  programs.direnv.enable = true;

  home.file.".config/nvim/" = {
    source = ../../nvim;
    recursive = true;
    force = true;
  };
  home.file.".scripts/" = {
    source = ../../scripts;
    recursive = true;
    executable = true;
    force = true;
  };
}
