# vim:ft=kitty
## name:     Kanagawa Wave
## upstream: https://github.com/rebelot/kanagawa.nvim

foreground              #DCD7BA
background              #1F1F28
selection_foreground    #C8C093
selection_background    #2D4F67

cursor                  #C8C093
cursor_text_color       #1F1F28
url_color               #72A7BC

active_border_color     #7E9CD8
inactive_border_color   #363646
bell_border_color       #E6C384

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #16161D
active_tab_background   #7E9CD8
inactive_tab_foreground #C8C093
inactive_tab_background #2A2A37
tab_bar_background      #16161D

mark1_foreground #1F1F28
mark1_background #7E9CD8
mark2_foreground #1F1F28
mark2_background #957FB8
mark3_foreground #1F1F28
mark3_background #7FB4CA

color0  #16161D
color8  #727169
color1  #C34043
color9  #E82424
color2  #76946A
color10 #98BB6C
color3  #C0A36E
color11 #E6C384
color4  #7E9CD8
color12 #7FB4CA
color5  #957FB8
color13 #938AA9
color6  #6A9589
color14 #7AA89F
color7  #C8C093
color15 #DCD7BA
